// Generated by web/emu/forge/gen_config.py from the firmware's sdkconfig: the framework's and the app's values.
#pragma once
#define CONFIG_APP_TZ "EST5EDT,M3.2.0,M11.1.0"
#define CONFIG_FORGE_SETUP_SSID "Forge-Setup"
#define CONFIG_FORGE_TLS_NAME "espforge device"
#define CONFIG_FORGE_REPO "TheMonkeyz/espforge"
#define CONFIG_FORGE_PRODUCT ""
#define CONFIG_FORGE_UA_COMMENT ""
#define CONFIG_FORGE_PORTAL_NAME ""
#define CONFIG_FORGE_OTA_SITE "https://themonkeyz.github.io/espforge/"
