#!/usr/bin/env python3
"""The files the firmware embeds (main/CMakeLists.txt EMBED_FILES), as C arrays for the browser build.

    python3 embed.py build/embed.c ttf=../../main/montserrat.ttf [name=path ...]

Each gives `const unsigned char name_start[]` and `const unsigned char *const name_end`: under ESP-IDF the app
declares them with asm("_binary_<file>_start"), which WebAssembly can't place, hence the app's one #ifdef EMU_BUILD:
    #ifdef EMU_BUILD
    extern const uint8_t ttf_start[];
    extern const uint8_t *const ttf_end;
    #else
    extern const uint8_t ttf_start[] asm("_binary_montserrat_ttf_start");
    extern const uint8_t ttf_end[]   asm("_binary_montserrat_ttf_end");
    #endif
"""
import sys

out = ['// Generated by web/emu/forge/embed.py: the files the firmware embeds, as arrays (the browser build).']
for arg in sys.argv[2:]:
    name, path = arg.split('=', 1)
    data = open(path, 'rb').read()
    rows = [','.join(str(b) for b in data[i:i + 32]) for i in range(0, len(data), 32)]
    out.append(f'const unsigned char {name}_start[] = {{\n' + ',\n'.join(rows) + '};')
    out.append(f'const unsigned char *const {name}_end = {name}_start + {len(data)};')
open(sys.argv[1], 'w', encoding='utf-8').write('\n'.join(out) + '\n')
