#!/usr/bin/env python3
"""The firmware's settings for the browser build, from an ESP-IDF sdkconfig, into the app's web/emu:

    python3 web/emu/forge/gen_config.py build/v55/sdkconfig web/emu      (or: make -C web/emu config)

- lv_kconfig.h: the CONFIG_LV_* lines, read by LVGL as under ESP-IDF (lv_conf_kconfig.h includes
  LV_CONF_KCONFIG_EXTERNAL_INCLUDE). Changed for the browser: the heap is the C library's (no PSRAM, no lvgl_mem.c).
- sdkconfig.h: the framework's and the app's values, the options declared in the project's own Kconfig files
  (main/Kconfig.projbuild, components/*/Kconfig, boards/*/*/Kconfig; any other with --keep NAME), which the shared
  headers and the app's code read (net.h, ota.h, svc.c, main.c's CONFIG_APP_TZ).

Rerun after changing those options (sdkconfig.defaults, Kconfig.projbuild), and commit both: CI builds the emulator
without building the firmware.
"""
import argparse
import glob
import os
import re

OVERRIDE = {
    'CONFIG_LV_USE_CUSTOM_MALLOC': None,          # forge_lvgl's lvgl_mem.c is ESP-only
    'CONFIG_LV_USE_CLIB_MALLOC': '1',             # (LVGL 9.2 derives CONFIG_LV_USE_STDLIB_MALLOC from it)
}

ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
ap.add_argument('sdkconfig')
ap.add_argument('out', help="the app's web/emu folder")
ap.add_argument('--keep', action='append', default=[], help='another option for sdkconfig.h (NAME, without CONFIG_)')
a = ap.parse_args()

root = os.path.join(a.out, '..', '..')
ours = set(a.keep)
for k in (glob.glob(os.path.join(root, 'main', 'Kconfig*')) + glob.glob(os.path.join(root, 'components', '*', 'Kconfig*'))
          + glob.glob(os.path.join(root, 'boards', '*', '*', 'Kconfig*'))):
    ours |= set(re.findall(r'^\s*(?:menu)?config\s+([A-Z0-9_]+)', open(k, encoding='utf-8').read(), re.M))

lv = ["// Generated by web/emu/forge/gen_config.py from the firmware's sdkconfig: the LVGL settings of the display.",
      '#pragma once', '#define CONFIG_LV_CONF_SKIP 1']
cfg = ["// Generated by web/emu/forge/gen_config.py from the firmware's sdkconfig: the framework's and the app's values.",
       '#pragma once']
for line in open(a.sdkconfig, encoding='utf-8'):
    m = re.match(r'^(CONFIG_([A-Z0-9_]+))=(.*)$', line.strip())
    if not m:
        continue
    k, name, v = m.groups()
    v = '1' if v == 'y' else v
    if k.startswith('CONFIG_LV_'):
        if k not in OVERRIDE:
            lv.append(f'#define {k} {v}')
    elif name in ours:
        cfg.append(f'#define {k} {v}')
lv += [f'#define {k} {v}' for k, v in OVERRIDE.items() if v is not None]
for name, lines in (('lv_kconfig.h', lv), ('sdkconfig.h', cfg)):
    with open(os.path.join(a.out, name), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'{os.path.join(a.out, name)}: {len(lines) - 2} values')
